### ISSUE TITLE
Did not understand some aspects of code

### ISSUE THREAD

**Issue by hgvk94** [hgvk94/z3#1]
### file : merge_generalizer.cpp

function : leq_monotonic_neg_k :
       It seems like you are checking the right hand side of the literal alone. I thought you had to check the right hand side of all the lemmas that match the pattern.

function : monotonic_coefficient :
       uni_consts is never used 
       the comment seems to say that A + B >=0 whereas A + B < 0 is being returned. 

function : merge_halfspaces :
         shouldn't the following this need to be checked ?
                          fst and scd have no variables on the left hand side.  
                          fst and scd have exactly one variable and no uninterpreted constants on the right hand side 

function : leq_monotonic_k :
       line: 88 : should this be mk_le instead of mk_eq ? 

### file : spacer_util.cpp 
 function : contains_nonlinear :
        seems like the whole ast_manager is being copied when calling the function
        line 1043 :  I think if the expression is var*const, the function will return true, but it should have returned false. 

### file : spacer_cluster.cpp 
 function : operator()
       I didn't understand what happens when a lemma is close to multiple lemmas ? It seems like the last antiUnifier pattern is stored along with all the previous neighbours ( even those that doesn't match the current pattern ). 

       If I understand correctly, the first neighbour of a lemma is the antiunifier pattern and the other neighbours are actual lemmas ?

**Comment by agurfinkel** [comment]
@hgvk94 you have many detailed questions (which is great!). Perhaps the most effective way is for you and I to go over the code together, fix what is clearly wrong, and send the rest of the questions to Jeff
